name: "Auto Release"

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  auto-release:
    name: "Automatic Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Build & test"
        run: |
          # Seus comandos de build e teste aqui
          echo "Build e teste completados com sucesso!"
        
      - name: "Set up Git"
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: "Incrementar versão da tag"
        id: increment_version
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          # Extrair a versão atual
          current_version=${latest_tag:1}
          # Incrementar a versão
          IFS='.' read -r major minor patch <<< "$current_version"
          patch=$((patch+1))
          new_version="v$major.$minor.$patch"
          echo "::set-output name=new_tag::$new_version"

      - name: "Criar e enviar tag"
        if: steps.increment_version.outputs.new_tag != ''
        run: |
          git tag ${{ steps.increment_version.outputs.new_tag }}
          git push origin ${{ steps.increment_version.outputs.new_tag }}
