name: Auto Tag

on:
  push:
    branches:
      - "**" # Executa em qualquer branch
  workflow_dispatch:
    # Permite acionar manualmente o fluxo de trabalho se necessário

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Determine next version
        id: next_version
        if: steps.latest_tag.outputs.tag == ''
        run: echo "::set-output name=version::1.0.0"

      - name: Determine next version
        id: next_version_2
        if: steps.latest_tag.outputs.tag != ''
        run: echo "::set-output name=version::$(echo "${{ steps.latest_tag.outputs.tag }}" | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')"

      - name: Push tag
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          git tag -a v${{ steps.next_version.outputs.version }} -m "Version ${{ steps.next_version.outputs.version }}"
          git push origin v${{ steps.next_version.outputs.version }}
