name: Auto Tag

on:
  # Executa em commits no branch padrão
  push:
    branches: ["master"]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Obter última tag
        id: get_last_tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"

      - name: Incrementar número da versão
        id: increment_version
        run: echo "::set-output name=version::$(echo ${{ steps.get_last_tag.outputs.tag }} | awk -F. '{{print $1"."$2"."$3 + 1}}')"

      - name: Criar nova tag
        id: create_tag
        run: echo "TAG=${{ steps.increment_version.outputs.version }}" >> $GITHUB_ENV

      - name: Enviar nova tag
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          git tag ${{ steps.increment_version.outputs.version }}
          git push origin ${{ steps.increment_version.outputs.version }}
