name: "Auto Release"

on:
  push:
    branches:
      - "master"
    tags:
      - "v*" # Ação acionada apenas por tags que começam com 'v'

jobs:
  auto-release:
    name: "Automatic Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Build & test"
        run: |
          # Seus comandos de build e teste aqui
          echo "Build and test completed successfully!"
        
      - name: "Set up Git"
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: "Generate Changelog and Release"
        if: ${{ github.ref != 'refs/heads/master' }}
        id: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: "latest"
          title: "isyuricunha / ${{ github.ref_name }}"
          files: |
            *

      - name: "Generate and Upload Changelog"
        if: steps.release.outputs.automatic_releases_tag != ''
        run: |
          # Gerar changelog a partir dos commits
          changelog=$(git log --pretty=format:"- %s (%h)" $(git describe --abbrev=0 --tags $(git describe --abbrev=0 --tags --abbrev=0..HEAD))..HEAD)

          # Atualizar notas de lançamento
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.release.outputs.automatic_releases_tag }} \
            -d '{"body": "'"$changelog"'"}'

      - name: "Increment Version"
        if: github.ref == 'refs/tags/v*' # Ação acionada apenas quando o push é para uma tag
        run: |
          # Extrair a versão atual da tag
          current_version=$(echo "${{ github.ref }}" | sed 's/v//')

          # Incrementar a versão
          new_version=$(echo "${current_version}" | awk -F '[.]' '{print $1"."$2"."$3+1}')

          # Criar 
