name: Auto Tag

on:
  # Executa em commits no branch padrão
  push:
    branches: ["master"]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Obter hash do último commit
        id: get_last_commit
        run: echo "::set-output name=commit::$(git log --format='%H' -n 1)"

      - name: Criar tag
        id: create_tag
        run: |
          git tag -a ${{ steps.get_last_commit.outputs.commit }} -m "$(git log --format='%s' -n 1)"
          git push origin ${{ steps.get_last_commit.outputs.commit }}
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
