name: Build App

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Publish release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          files: |
            *.*
