name: Auto Tag

on:
  push:
    branches:
      - "**" # Executa em qualquer branch
  workflow_dispatch:
    # Permite acionar manualmente o fluxo de trabalho se necessário

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Create tag
        if: steps.latest_tag.outputs.tag == ''
        id: tag
        run: echo "TAG=v1.0.0" >> $GITHUB_ENV

      - name: Push tag
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          if [ -z "${{ steps.latest_tag.outputs.tag }}" ]; then
            git tag v1.0.0
            git push origin v1.0.0
          else
            git push origin ${{ steps.latest_tag.outputs.tag }}
          fi
