name: Auto Tag

on:
  # Execute when there is a push on the default branch
  push:
    branches: ["master"]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Check if tag exists locally
        run: |
          if git rev-parse ${{ steps.latest_tag.outputs.tag }} >/dev/null 2>&1; then
            echo "Tag ${{ steps.latest_tag.outputs.tag }} already exists locally."
          else
            echo "Tag ${{ steps.latest_tag.outputs.tag }} does not exist locally."
          fi

      - name: Fetch tags from the remote repository
        run: git fetch --tags

      - name: Create and push tag if it doesn't exist
        if: steps.latest_tag.outputs.tag == ''
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          git tag v1.0.0
          git push origin v1.0.0

      - name: Push the updated tag
        if: steps.latest_tag.outputs.tag != ''
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          git push origin ${{ steps.latest_tag.outputs.tag }}
