name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

        
      - name: commit readme
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      
      - name: "Build & test"
        run: |
          echo "done!"
          
      - name: Create Stable release
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: ${{ contains(github.ref_name, '-') }}
          title: librime ${{ github.ref_name }}
          files: |
            *
