name: Release CI

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Stable release
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          title: isyuricunha ${{ github.ref_name }}
          files: |
            *.*
