name: Auto Tag

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Create tag
        if: steps.latest_tag.outputs.tag == ''
        id: tag
        run: |
          echo "TAG=v1.0.0" >> $GITHUB_ENV
          git tag v1.0.0

      - name: Push tag
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          git push origin ${{ steps.latest_tag.outputs.tag }}
